---
abstract: 'perl interface to libuv'
author:
  - 'Daisuke Murase <typester@cpan.org>'
build_requires:
  Devel::PPPort: 3.2
  ExtUtils::MakeMaker: 6.36
  Test::TCP: 0
configure_requires:
  Devel::PPPort: 3.2
  ExtUtils::MakeMaker: 6.36
  ExtUtils::ParseXS: 2.21
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: UV
no_index:
  directory:
    - example
    - inc
    - t
requires:
  XSLoader: 0.02
version: 0.12
